# **************************************************************************
# *
# * Authors:     David Herreros Calero (dherreros@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

from os.path import abspath
import numpy as np

from pwem.convert import toCIF, Ccp4Header
from pwem.convert.atom_struct import toPdb, AtomicStructHandler, addScipionAttribute
from pwem.objects import SetOfAtomStructs, AtomStruct
from pwem.protocols import ProtAnalysis3D

from pyworkflow.protocol import PointerParam, FloatParam, MultiPointerParam, IntParam, BooleanParam
from pyworkflow import BETA
import pyworkflow.utils as pwutils

import mapq


class ProtMapQ(ProtAnalysis3D):
    """
    Computes Q-scores for atomic structures relative to a cryo-EM density
    map. The protocol evaluates how well individual atoms and complete
    molecular models agree with the experimental density, providing a
    quantitative measure of local structural resolvability.

    AI Generated:

    MapQ Score Computation (ProtMapQ) — User Manual
        Overview

        The MapQ protocol evaluates the agreement between one cryo-EM map and one
        or several atomic models by calculating Q-scores. In structural biology,
        Q-scores provide a practical and biologically meaningful way to estimate
        how well each atom of a model is supported by the experimental density.
        Rather than simply measuring global map-to-model similarity, the protocol
        focuses on local resolvability, making it especially useful when judging
        the reliability of side-chain placement, ligand interpretation, or subtle
        conformational differences.

        For biological users, this analysis is particularly valuable after model
        building, model refinement, or comparative interpretation of several
        candidate structures against the same reconstruction. It allows direct
        assessment of whether atomic features are genuinely supported by the map
        or whether certain regions should be interpreted more cautiously.

        Inputs and Biological Context

        The protocol requires a three-dimensional cryo-EM density map together
        with one or more atomic structures. The map acts as the experimental
        reference, while each input model is evaluated independently within that
        density context. A common use case is the comparison of several refined
        models, alternative conformations, homolog-based fits, or structures
        generated by different refinement strategies.

        In practical cryo-EM work, the most meaningful results are obtained when
        the atomic models represent the same biological state captured by the map.
        Large conformational discrepancies or strongly incomplete models can
        produce low Q-scores that reflect biological mismatch rather than local
        structural quality.

        Map and Structure Alignment

        A critical prerequisite for meaningful Q-score interpretation is correct
        spatial registration between the density map and the atomic model. When
        models are not already placed in the correct coordinate frame, an initial
        fitting step becomes essential. Without accurate alignment, local density
        agreement becomes biologically misleading because poor scores may simply
        reflect positional mismatch rather than true lack of structural support.

        For most users, automatic fitting is especially useful when structures
        originate from external databases, homologous models, or previous
        refinement rounds. When models have already been carefully refined
        directly into the map, additional fitting may not be necessary.

        Resolution and Expected Interpretation

        The interpretation of Q-scores depends strongly on map resolution. At
        higher resolution, well-resolved side chains and backbone features are
        expected to produce higher local scores. At lower resolution, reduced
        atomic detail naturally lowers the expected local agreement, even for
        biologically correct models.

        For this reason, providing the experimental resolution helps place the
        resulting values into a realistic structural context. Biological users
        should avoid comparing absolute Q-scores from datasets of very different
        resolution without considering this dependence.

        Local Structural Quality

        One of the main strengths of Q-score analysis is that it provides
        atom-level information. This makes it possible to identify specific
        residues, ligands, cofactors, flexible loops, or side chains that are
        strongly supported by the density, as well as those that are weakly
        resolved.

        In cryo-EM interpretation, this distinction is extremely important.
        Regions with low local Q-scores may indicate intrinsic flexibility,
        partial occupancy, local disorder, compositional heterogeneity, or model
        overinterpretation. Conversely, consistently high local values often mark
        structurally rigid regions that can be interpreted with greater
        confidence.

        Per-Atom Annotation and Downstream Use

        The protocol produces output structures in which Q-score information is
        preserved as atom-associated metadata. This allows downstream biological
        analysis beyond simple numerical reporting. Users can visualize local
        confidence directly on the structure, inspect problematic regions, and
        compare equivalent residues across different candidate models.

        In practice, this is particularly useful when deciding between competing
        side-chain placements, evaluating flexible interfaces, validating ligand
        environments, or preparing figures for publication where local map
        support must be demonstrated clearly.

        Comparison of Multiple Models

        When several atomic models are evaluated against the same map, the
        protocol becomes a convenient comparative validation framework. Mean
        Q-scores provide a compact global summary, but the most biologically
        meaningful interpretation often comes from examining how local scores are
        distributed across domains, chains, and functionally relevant residues.

        Two models may have similar global averages yet differ strongly in
        flexible loops, catalytic residues, interaction interfaces, or ligand
        binding pockets. For this reason, global statistics should be considered
        as an entry point rather than a final biological conclusion.

        Practical Recommendations

        In routine cryo-EM workflows, Q-score analysis is most informative after
        model refinement has converged and the user wishes to evaluate local
        interpretability. It is especially valuable before deposition, before
        comparative biological interpretation, or when deciding whether a region
        supports atomic-level claims.

        When low scores appear, biological interpretation should be cautious.
        Poor local values do not necessarily indicate a wrong model. They may
        instead reflect genuine structural mobility, partial occupancy, local
        heterogeneity, radiation damage, or insufficient local resolution.

        Final Perspective

        For cryo-EM structural analysis, Q-score estimation is not merely a
        technical validation procedure but a biologically important measure of
        how confidently atomic detail can be interpreted. By linking local model
        geometry directly to experimental density support, the protocol helps
        distinguish robust structural conclusions from regions that require
        greater caution. This makes it especially valuable for modern
        high-resolution cryo-EM studies where biological interpretation often
        depends on subtle local structural features.
    """
    _label = 'compute q-scores'
    _devStatus = BETA
    _ATTRNAME = "MapQ_Score"
    _OUTNAME = "scoredStructures"

    # --------------------------- DEFINE param functions ------------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('inputVol', PointerParam, pointerClass="Volume", label="Input map",
                      help='Volume to compare to PDBs', important=True)
        form.addParam('pdbs', MultiPointerParam, pointerClass="AtomStruct", important=True,
                      label="Input structures",
                      help='PDBs to compare to input map')
        form.addParam('mapRes', FloatParam, allowsNull=True,
                      label = "Map resolution",
                      help = "Optional - Default is 3.0 - Specifies resolution of map; it is used to output perresidue "
                             "statistics along with expected Q-score at this resolution")
        form.addParam('bFactor', IntParam, allowsNull=True,
                      label="B-factor",
                      help="Optional - If specified, a separate pdb file will be "
                           "written where bfactor=N*(1-Qscore) for each atom.")
        form.addParam('sigma', FloatParam, allowsNull=True,
                      label="Sigma",
                      help="Optional – default is 0.6 – specifies width of reference Gaussian in Å ")
        form.addParam('autoFit', BooleanParam, default=True, label="Auto fit map and structures?",
                      help="If true, the map and structures will be automatically aligned with Chimera. "
                           "Otherwise, map and structures will be assumed to be aligned")
        form.addParallelSection(threads=4, mpi=0)

    # --------------------------- INSERT steps functions ------------------------
    def _insertAllSteps(self):
        self._insertFunctionStep(self.convertInputStep)
        self._insertFunctionStep(self.computeQScoresStep)
        self._insertFunctionStep(self.createOutputStep)

    # --------------------------- STEPS functions -------------------------------
    def convertInputStep(self):
        volFile = self.inputVol.get().getFileName()
        sampling = self.inputVol.get().getSamplingRate()
        origin = self.inputVol.get().getShiftsFromOrigin()
        self.volOutFile = abspath(self._getExtraPath('map.mrc'))
        Ccp4Header.fixFile(volFile, self.volOutFile, origin, sampling,
                           Ccp4Header.START)

        self.cifOutFile = []
        self.pdbOutFile = []
        for pdb in self.pdbs:
            cifFile = pdb.get().getFileName()
            baseName = pwutils.removeBaseExt(cifFile)
            self.cifOutFile.append(abspath(self._getExtraPath('%s.cif' % baseName)))  #############################
            self.pdbOutFile.append(abspath(self._getExtraPath('%s.pdb' % baseName)))

            h = AtomicStructHandler()
            h.read(cifFile)
            h.writeAsCif(self.cifOutFile[-1])

            #### CHIMERAX
            if self.autoFit.get():
                print("Fitting %s into map..." % baseName)
                scriptFile = self._getTmpPath("fitting.py")
                with open(scriptFile, 'w') as fhCmd:  # Using 'with' ensures the file is properly closed
                    fhCmd.write("from chimerax.core.commands import run\n")
                    fhCmd.write("run(session, 'open %s')\n" % self.cifOutFile[-1])
                    fhCmd.write("run(session, 'open %s')\n" % self.volOutFile)
                    fhCmd.write("run(session, 'fitmap #1 inMap #2')\n")
                    fhCmd.write("run(session, 'save %s models #1 relModel #2')\n" % self.pdbOutFile[-1])
                    fhCmd.write("run(session, 'exit')\n")  # Ensure ChimeraX exits after running the script
                args = "--nogui --script %s" % scriptFile
                self.runJob(mapq.Plugin.getChimeraXProgram(), args)

    def computeQScoresStep(self):
        args = '%s %s ' % (mapq.Plugin.getChimeraPath(), self.volOutFile)
        args += " ".join(self.pdbOutFile)

        if self.mapRes.get():
            args += " res=%f" % self.mapRes.get()

        if self.bFactor.get():
            args += ' bfactor=%d' % self.bFactor.get()

        if self.sigma.get():
            args += ' sigma=%f' % self.sigma.get()

        args += " np=%d" % self.numberOfThreads.get()

        python_file, mapq_file = mapq.Plugin.getMapQProgram()
        self.runJob(python_file, mapq_file + " " + args)

    def createOutputStep(self):
        outStructFileBase = self._getExtraPath('{}.cif')
        ASH = AtomicStructHandler()
        outSet = SetOfAtomStructs.create(self._getPath())
        for pdb in self.pdbs:
            pdbFile = pdb.get().getFileName()
            baseName = pwutils.removeBaseExt(pdbFile)
            outStructFileName = outStructFileBase.format(baseName)
            mapq_pdb = self._getExtraPath(baseName + ".pdb__Q__map.mrc.pdb")
            ASH.read(mapq_pdb)
            mapQ_dict = self.createMapQDict(mapq_pdb)
            inpAS = toCIF(pdbFile, outStructFileName)
            cifDic = ASH.readLowLevel(inpAS)
            cifDic = addScipionAttribute(cifDic, mapQ_dict, self._ATTRNAME, recipient = 'atoms')
            ASH._writeLowLevel(outStructFileName, cifDic)

            outAS = AtomStruct()
            outAS.setFileName(outStructFileName)
            outSet.append(outAS.clone())

        self._defineOutputs(scoredStructures=outSet)
        for pdb in self.pdbs:
            self._defineSourceRelation(pdb, outSet)

    # --------------------------- UTILS functions -------------------------------
    def moveOriginTo(self, newOrigin, handler):
        centerMass = handler.centerOfMass(geometric=True)
        for atom in handler.getStructure().get_atoms():
            coords = atom.get_coord()
            atom.coord = coords + np.asarray(newOrigin) - np.asarray(centerMass)

    def createMapQDict(self, mapq_pdb):
            mapQ_dict = {}
            
            with open(mapq_pdb, 'r') as f:
                for line in f:
                    # El tipo de registro (ATOM/HETATM) está en los primeros 6 caracteres
                    record_type = line[0:6].strip()
                    
                    if record_type in ['ATOM', 'HETATM']:
                        try:
                            # Extraemos los campos usando los índices definidos en tu colspecs original
                            # chainid: posición 21 (índice 21:22)
                            # serial: posición 6-11 (índice 6:11)
                            # Q_score: posición 60-66 (índice 60:66)
                            
                            chain_id = line[21:22].strip()
                            serial = line[6:11].strip()
                            q_score = line[60:66].strip()
                            
                            # Creamos la llave con el formato "chainid:serial"
                            key = f"{chain_id}:{int(serial)}"
                            mapQ_dict[key] = q_score
                            
                        except (ValueError, IndexError):
                            # En caso de que una línea esté mal formateada o vacía
                            continue
                            
            return mapQ_dict

    # --------------------------- INFO functions ------------------------------
    def _methods(self):
        methods = []
        methods.append('QScore computation using MapQ')
        return methods

    def _summary(self):
        summary = []
        if not self.isFinished():
            summary.append("QScores not ready yet.")

        if self.getOutputsSize() >= 1:
            summary.append("*Mean Q-Scores:*")
            ASH = AtomicStructHandler()
            for struct in self.scoredStructures:
                fileName = struct.getFileName()
                fields = ASH.readLowLevel(fileName)
                attributes = fields["_scipion_attributes.name"]
                values = fields["_scipion_attributes.value"]
                mapq_scores = [float(value) for attribute, value in zip(attributes, values)
                               if attribute == self._ATTRNAME]
                mean_score = sum(mapq_scores) / len(mapq_scores)
                summary.append("      - %s --> %.4f" % (pwutils.removeBaseExt(fileName), mean_score))
        return summary
